version: '3.3'

services:
  db_postgresql:
    image: postgres:16.2
    container_name: challenge_api
    restart: always
    environment:
      - POSTGRES_DB=db_challenge
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
